# Generated by Django 4.2.1 on 2023-06-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptols',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255, null=True)),
                ('priceChange', models.FloatField(max_length=255, null=True)),
                ('priceChangePercent', models.FloatField(max_length=255, null=True)),
                ('weightedAvgPrice', models.FloatField(max_length=255, null=True)),
                ('prevClosePrice', models.FloatField(max_length=255, null=True)),
                ('lastPrice', models.FloatField(max_length=255, null=True)),
                ('lastQty', models.FloatField(max_length=255, null=True)),
                ('bidPrice', models.FloatField(max_length=255, null=True)),
                ('bidQty', models.FloatField(max_length=255, null=True)),
                ('askPrice', models.FloatField(max_length=255, null=True)),
                ('askQty', models.FloatField(max_length=255, null=True)),
                ('openPrice', models.FloatField(max_length=255, null=True)),
                ('highPrice', models.FloatField(max_length=255, null=True)),
                ('lowPrice', models.FloatField(max_length=255, null=True)),
                ('volume', models.FloatField(max_length=255, null=True)),
                ('quoteVolume', models.FloatField(max_length=255, null=True)),
                ('openTime', models.FloatField(max_length=255, null=True)),
                ('closeTime', models.FloatField(max_length=255, null=True)),
                ('firstId', models.FloatField(max_length=255, null=True)),
                ('lastId', models.FloatField(max_length=255, null=True)),
                ('count', models.FloatField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phone', models.IntegerField(null=True)),
                ('joined_date', models.DateField(null=True)),
            ],
        ),
    ]
